services:

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    mem_limit: 512m
    cpu_count: 1
    healthcheck:
      test: [ "CMD", "/opt/kafka/bin/kafka-cluster.sh", "cluster-id", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_HEAP_OPTS: "-Xms128m -Xmx256m"
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
    networks:
      - core-infra

  generator:
    image: udhayarajan/core-infra-generator:latest
    build:
      context: .
      dockerfile: generator/Dockerfile
    container_name: generator
    mem_limit: 64m
    cpu_count: 2
    networks:
      - core-infra
    depends_on:
      broker:
        condition: service_healthy
    environment:
      "KAFKA_BROKER": "broker:29092"
    command: [ "-max=50_000_000" ] # it's event count


  processor:
    image: udhayarajan/core-infra-processor:latest
    mem_limit: 2048m
    cpu_count: 2
    build:
      context: .
      dockerfile: processor/Dockerfile
    container_name: processor
    networks:
      - core-infra
    depends_on:
      broker:
        condition: service_healthy
    environment:
      "KAFKA_BROKER": "broker:29092"
    command: [ "-max=50_000_000", "-batch=100_000_000" ] # it's batch size in bytes (is equal to 100MB)

  validator:
    image: udhayarajan/core-infra-validator:latest
    cpu_count: 1
    mem_limit: 64m
    build:
      context: .
      dockerfile: validator/Dockerfile
    container_name: validator
    volumes:
      - ./:./
    networks:
      - core-infra
    depends_on:
      broker:
        condition: service_healthy
    environment:
      "KAFKA_BROKER": "broker:29092"

networks:
  core-infra:
    driver: bridge
